### ISSUE TITLE
How to find key

### ISSUE THREAD

**Issue by zakblacki** [Nomost80/xor-decryption#1]
Nice project thanks for sharing !
How did you get the key to decrypt 
Can you add the documentation of the project 

Thanks

**Comment by Nomost80** [comment]
Thanks.
I guess you received encrypted files.
You need to have nodejs and npm on your system.
Add your files in the resources/encrypted_files folder.
Then you can do npm install and npm run start.
Normally it should works if your files were encrypted by a xor.
